### ISSUE TITLE
got an unexpected keyword argument 'model_name_or_path'

### ISSUE THREAD

**Issue by Flagami** [EasyJailbreak/EasyJailbreak#24]
Traceback (most recent call last):
  File "/storage/zhaofulai/projects/EasyJailbreak/tutorial/diy_attacker.py", line 5, in <module>
    target_model = HuggingfaceModel(model_name_or_path='meta-llama/Llama-2-7b-chat-hf',
TypeError: HuggingfaceModel.__init__() got an unexpected keyword argument 'model_name_or_path'

I got this error while running the demo scripts of diy attack parts

**Comment by Isaac-theori** [comment]
I'm having the same problem.

**Comment by marcorosa** [comment]
meta's models require authentication. Did you export the huggingface token before running that script?

**Comment by Jeff-Huang-SHU** [comment]
I encountered the same problem. It seems there's no input keyword named 'model_name_or_path', but 'model', 'tokenizer', 'model_name'.

**Comment by LemXiong** [comment]
> Traceback (most recent call last): File "/storage/zhaofulai/projects/EasyJailbreak/tutorial/diy_attacker.py", line 5, in target_model = HuggingfaceModel(model_name_or_path='meta-llama/Llama-2-7b-chat-hf', TypeError: HuggingfaceModel.**init**() got an unexpected keyword argument 'model_name_or_path'
> 
> I got this error while running the demo scripts of diy attack parts

Hi, it should be
```
from easyjailbreak.models import from_pretrained
model = from_pretrained(model_name_or_path='meta-llama/Llama-2-7b-chat-hf', model_name='llama-2')
```
You can check the file ./easyjailbreak/models/huggingface_model.py for details.
