### ISSUE TITLE
Error happens when using OpenAI models as attack model.

### ISSUE THREAD

**Issue by Junjie-Chu** [EasyJailbreak/EasyJailbreak#31]
Hello,

When using OpenAI models as attack model in TAP&PAIR, an error happens:
```
Traceback (most recent call last):
  File "PATH/easyjailbreak/run_PAIR.py", line 43, in <module>
    attacker.attack(save_path='PATH')
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/attacker/PAIR_chao_2023.py", line 273, in attack
    self.processed_instances.add(self.single_attack(instance))
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/attacker/PAIR_chao_2023.py", line 213, in single_attack
    new_instance = self.mutations[0](jailbreak_dataset=JailbreakDataset([stream]),
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/mutation/mutation_base.py", line 37, in __call__
    mutated_instance_list = self._get_mutated_instance(instance, *args, **kwargs)
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/mutation/generation/historical_insight.py", line 35, in _get_mutated_instance
    mutated_text = self.historical_insight(seeds, prompt_format)
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/mutation/generation/historical_insight.py", line 49, in historical_insight
    return self.model.generate(prompt_format)
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/easyjailbreak/models/openai_model.py", line 42, in generate
    response = self.client.chat.completions.create(
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "PATH/easy_jailbreak_env/lib/python3.10/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid type for 'messages[1].content[0]': expected an object, but got a string instead.", 'type': 'invalid_request_error', 'param': 'messages[1].content[0]', 'code': 'invalid_type'}}
```
code:
```
dataset = JailbreakDataset('AdvBench')[:1]

attack_model = OpenaiModel(model_name='gpt-4',
                          api_keys='sk-key')
target_model = OpenaiModel(model_name='gpt-4',
                         api_keys='sk-key')
eval_model = OpenaiModel(model_name='gpt-4',
                         api_keys='sk-key')

attacker = PAIR(attack_model=attack_model,
                target_model=target_model,
                eval_model=eval_model,
                jailbreak_datasets=dataset,
                max_n_attack_attempts = 30,
                n_streams = 3,
                n_iterations = 10,
                attack_max_n_tokens=300,
                )
```

When use som local model like llama2/vicuna as the attack model, the issue not happen. Thus I conjecture that the problem is caused by ```attack_model = OpenaiModel```.

**Comment by tamir-alltrue-ai** [comment]
I can reproduce this

**Comment by yyytwo** [comment]
怎么操作呢，可以交流一下吗
